// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: dataserver.proto

package dataserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFileBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	BlockID  int64  `protobuf:"varint,2,opt,name=blockID,proto3" json:"blockID,omitempty"`
}

func (x *GetFileBlockRequest) Reset() {
	*x = GetFileBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileBlockRequest) ProtoMessage() {}

func (x *GetFileBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileBlockRequest.ProtoReflect.Descriptor instead.
func (*GetFileBlockRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileBlockRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFileBlockRequest) GetBlockID() int64 {
	if x != nil {
		return x.BlockID
	}
	return 0
}

type GetFileBlockReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFileBlockReply) Reset() {
	*x = GetFileBlockReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileBlockReply) ProtoMessage() {}

func (x *GetFileBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileBlockReply.ProtoReflect.Descriptor instead.
func (*GetFileBlockReply) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileBlockReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFileBlocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *GetFileBlocksRequest) Reset() {
	*x = GetFileBlocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileBlocksRequest) ProtoMessage() {}

func (x *GetFileBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetFileBlocksRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileBlocksRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetFileBlocksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName   string                           `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	DataBlocks []*GetFileBlocksReply_DataBlocks `protobuf:"bytes,2,rep,name=dataBlocks,proto3" json:"dataBlocks,omitempty"`
}

func (x *GetFileBlocksReply) Reset() {
	*x = GetFileBlocksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileBlocksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileBlocksReply) ProtoMessage() {}

func (x *GetFileBlocksReply) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileBlocksReply.ProtoReflect.Descriptor instead.
func (*GetFileBlocksReply) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileBlocksReply) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFileBlocksReply) GetDataBlocks() []*GetFileBlocksReply_DataBlocks {
	if x != nil {
		return x.DataBlocks
	}
	return nil
}

type PutFileBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName  string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	BlockID   int64  `protobuf:"varint,2,opt,name=blockID,proto3" json:"blockID,omitempty"`
	BlockSize int64  `protobuf:"varint,3,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	Data      []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PutFileBlockRequest) Reset() {
	*x = PutFileBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutFileBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileBlockRequest) ProtoMessage() {}

func (x *PutFileBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileBlockRequest.ProtoReflect.Descriptor instead.
func (*PutFileBlockRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{4}
}

func (x *PutFileBlockRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PutFileBlockRequest) GetBlockID() int64 {
	if x != nil {
		return x.BlockID
	}
	return 0
}

func (x *PutFileBlockRequest) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *PutFileBlockRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutFileBlockReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *PutFileBlockReply) Reset() {
	*x = PutFileBlockReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutFileBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileBlockReply) ProtoMessage() {}

func (x *PutFileBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileBlockReply.ProtoReflect.Descriptor instead.
func (*PutFileBlockReply) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{5}
}

func (x *PutFileBlockReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetFileBlocksReply_DataBlocks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockID   int64  `protobuf:"varint,1,opt,name=blockID,proto3" json:"blockID,omitempty"`
	BlockSize int64  `protobuf:"varint,2,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFileBlocksReply_DataBlocks) Reset() {
	*x = GetFileBlocksReply_DataBlocks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileBlocksReply_DataBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileBlocksReply_DataBlocks) ProtoMessage() {}

func (x *GetFileBlocksReply_DataBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileBlocksReply_DataBlocks.ProtoReflect.Descriptor instead.
func (*GetFileBlocksReply_DataBlocks) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetFileBlocksReply_DataBlocks) GetBlockID() int64 {
	if x != nil {
		return x.BlockID
	}
	return 0
}

func (x *GetFileBlocksReply_DataBlocks) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *GetFileBlocksReply_DataBlocks) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_dataserver_proto protoreflect.FileDescriptor

var file_dataserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x4b,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x1a, 0x58, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x7d, 0x0a, 0x13, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x23, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x32, 0x85, 0x02, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x1f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x20, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x50, 0x75,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1f, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x3f, 0x5a, 0x3d,
	0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x65, 0x6e, 0x67, 0x72, 0x2e, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x6f, 0x69, 0x73, 0x2e, 0x65, 0x64, 0x75, 0x2f, 0x63, 0x6b, 0x63, 0x68, 0x75, 0x32, 0x2f,
	0x63, 0x73, 0x34, 0x32, 0x35, 0x2d, 0x6d, 0x70, 0x33, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataserver_proto_rawDescOnce sync.Once
	file_dataserver_proto_rawDescData = file_dataserver_proto_rawDesc
)

func file_dataserver_proto_rawDescGZIP() []byte {
	file_dataserver_proto_rawDescOnce.Do(func() {
		file_dataserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataserver_proto_rawDescData)
	})
	return file_dataserver_proto_rawDescData
}

var file_dataserver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dataserver_proto_goTypes = []interface{}{
	(*GetFileBlockRequest)(nil),           // 0: dataserver.GetFileBlockRequest
	(*GetFileBlockReply)(nil),             // 1: dataserver.GetFileBlockReply
	(*GetFileBlocksRequest)(nil),          // 2: dataserver.GetFileBlocksRequest
	(*GetFileBlocksReply)(nil),            // 3: dataserver.GetFileBlocksReply
	(*PutFileBlockRequest)(nil),           // 4: dataserver.PutFileBlockRequest
	(*PutFileBlockReply)(nil),             // 5: dataserver.PutFileBlockReply
	(*GetFileBlocksReply_DataBlocks)(nil), // 6: dataserver.GetFileBlocksReply.DataBlocks
}
var file_dataserver_proto_depIdxs = []int32{
	6, // 0: dataserver.GetFileBlocksReply.dataBlocks:type_name -> dataserver.GetFileBlocksReply.DataBlocks
	0, // 1: dataserver.DataServer.GetFileBlock:input_type -> dataserver.GetFileBlockRequest
	2, // 2: dataserver.DataServer.GetFileBlocks:input_type -> dataserver.GetFileBlocksRequest
	4, // 3: dataserver.DataServer.PutFileBlock:input_type -> dataserver.PutFileBlockRequest
	1, // 4: dataserver.DataServer.GetFileBlock:output_type -> dataserver.GetFileBlockReply
	3, // 5: dataserver.DataServer.GetFileBlocks:output_type -> dataserver.GetFileBlocksReply
	5, // 6: dataserver.DataServer.PutFileBlock:output_type -> dataserver.PutFileBlockReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dataserver_proto_init() }
func file_dataserver_proto_init() {
	if File_dataserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileBlockReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileBlocksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileBlocksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutFileBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutFileBlockReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileBlocksReply_DataBlocks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataserver_proto_goTypes,
		DependencyIndexes: file_dataserver_proto_depIdxs,
		MessageInfos:      file_dataserver_proto_msgTypes,
	}.Build()
	File_dataserver_proto = out.File
	file_dataserver_proto_rawDesc = nil
	file_dataserver_proto_goTypes = nil
	file_dataserver_proto_depIdxs = nil
}
